version: '3.8'

services:
  # Presentation Layer (Local)
  presentation-layer:
    build:
      context: .
    ports:
      - "4000:4000"
    depends_on:
      business-logic-layer:
        condition: service_healthy
    networks:
      - dev-network

  # Business Logic Layer (From GitHub)
  business-logic-layer:
    build:
      context: https://github.com/alejandronoss1017/dev-hub-services.git#develop
    ports:
      - "5000:5000"
    depends_on:
      persistence-layer:
        condition: service_healthy
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  # Persistence Layer (From GitHub)
  persistence-layer:
    build:
      context: https://github.com/alejandronoss1017/dev-hub-data.git#develop
      args:
        - DATABASE_URL=${DATABASE_URL}
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    networks:
      - dev-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

networks:
  dev-network:
    driver: bridge