networks:
  dev-hub:
    name: dev-hub

services:

  # Business Logic Layer (From GitHub)
  business-logic-layer:
    build:
      context: https://github.com/alejandronoss1017/dev-hub-services.git#develop
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    expose:
      - "5000"
    networks:
      - dev-hub
    depends_on:
      - persistence-layer

  # Persistence Layer (From GitHub)
  persistence-layer:
    extends:
      file: https://github.com/alejandronoss1017/dev-hub-data.git#develop
      service: data-layer
    networks:
      - dev-hub
    depends_on:
      - postgres-database

  pg-admin:
    image: dpage/pgadmin4:8.8
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - dev-hub
    depends_on:
      - postgres-database
          
  # Services from dev-hub-data
  postgres-database:
    extends:
      file: https://github.com/alejandronoss1017/dev-hub-data.git#develop:docker-compose.yaml
      service: postgres-database
    networks:
      - dev-hub

volumes:
  pgadmin_data: